# Generated by Django 4.1.7 on 2023-06-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagan',
            name='id_score',
            field=models.ManyToManyField(blank=True, to='bagan.score'),
        ),
    ]
