# Generated by Django 4.1.7 on 2023-06-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagan', '0002_bagan_id_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bagan',
            name='id_score',
        ),
        migrations.AddField(
            model_name='detailbagann',
            name='id_scoredetail',
            field=models.ManyToManyField(blank=True, to='bagan.scoredetail'),
        ),
    ]
