# Generated by Django 4.1.7 on 2023-06-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagan', '0003_remove_bagan_id_score_detailbagann_id_scoredetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoredetail',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
