# Generated by Django 4.1.7 on 2023-06-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagan', '0004_scoredetail_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalScore',
            fields=[
                ('id_totalscore', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='scoredetail',
            name='total',
        ),
        migrations.AddField(
            model_name='score',
            name='id_totalscore',
            field=models.ManyToManyField(blank=True, to='bagan.totalscore'),
        ),
    ]
