# Generated by Django 4.1.7 on 2023-06-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagan', '0005_totalscore_remove_scoredetail_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalscore',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
